# Generated by Django 4.2.26 on 2025-12-31 14:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "تم الإنشاء"),
                            ("updated", "تم التحديث"),
                            ("status_changed", "تغيير الحالة"),
                            ("priority_changed", "تغيير الأولوية"),
                            ("assigned", "تم التعيين"),
                            ("commented", "تم التعليق"),
                            ("resolved", "تم الحل"),
                            ("rejected", "تم الرفض"),
                            ("closed", "تم الإغلاق"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "performed_by_name",
                    models.CharField(max_length=200, verbose_name="نفذ بواسطة"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "old_value",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="القيمة القديمة",
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="القيمة الجديدة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
            ],
            options={
                "verbose_name": "سجل نشاط",
                "verbose_name_plural": "سجلات الأنشطة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=200, verbose_name="اسم الكاتب"),
                ),
                (
                    "author_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                ("comment_text", models.TextField(verbose_name="التعليق")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="التعليقات الداخلية لا تظهر للعموم",
                        verbose_name="ملاحظة داخلية",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comment_attachments/",
                        verbose_name="مرفق",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تعليق",
                "verbose_name_plural": "التعليقات",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_ticket", "طلب جديد"),
                            ("status_change", "تغيير حالة"),
                            ("new_comment", "تعليق جديد"),
                            ("assigned", "تم التعيين"),
                            ("due_soon", "موعد قريب"),
                            ("overdue", "متأخر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="المستلم"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="تم الإرسال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القراءة"
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        help_text="من 1 إلى 5 نجوم",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="الملاحظات"),
                ),
                (
                    "rated_by_name",
                    models.CharField(max_length=200, verbose_name="المقيّم"),
                ),
                (
                    "rated_by_email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقييم"
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم",
                "verbose_name_plural": "التقييمات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="رئيس القسم"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="department",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="الهاتف"
            ),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="اللون بصيغة hex (مثل: #FF5733)",
                max_length=20,
                null=True,
                verbose_name="اللون",
            ),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="estimated_time",
            field=models.IntegerField(
                blank=True,
                help_text="الوقت المتوقع لإنجاز هذا النوع من الطلبات",
                null=True,
                verbose_name="الوقت المتوقع (بالساعات)",
            ),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="اسم أيقونة Bootstrap Icons (مثل: bi-laptop)",
                max_length=50,
                null=True,
                verbose_name="أيقونة",
            ),
        ),
        migrations.AddField(
            model_name="requesttype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="الموعد النهائي لإنجاز الطلب",
                null=True,
                verbose_name="تاريخ الاستحقاق",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_urgent",
            field=models.BooleanField(
                default=False,
                help_text="حدد إذا كان الطلب يحتاج معالجة عاجلة",
                verbose_name="طلب عاجل",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="رقم الهاتف"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_notes",
            field=models.TextField(
                blank=True,
                help_text="تفاصيل حول كيفية حل الطلب",
                null=True,
                verbose_name="ملاحظات الحل",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحل"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                blank=True,
                help_text="يتم إنشاؤه تلقائياً",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="رقم الطلب",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="عدد المشاهدات"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "منخفضة"),
                    ("medium", "متوسطة"),
                    ("high", "عالية"),
                    ("urgent", "عاجلة"),
                ],
                default="medium",
                max_length=20,
                verbose_name="الأولوية",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("in_progress", "قيد التنفيذ"),
                    ("on_hold", "معلق مؤقتاً"),
                    ("resolved", "تم الحل"),
                    ("rejected", "مرفوض"),
                    ("closed", "مغلق"),
                ],
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["-created_at"], name="tickets_tic_created_c2132d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="tickets_tic_status_0e5646_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority"], name="tickets_tic_priorit_0bec9b_idx"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="tickets.ticket",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المستلم",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tickets.ticket",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tickets.ticket",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="performed_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="tickets.ticket",
                verbose_name="الطلب",
            ),
        ),
    ]
